cmake_minimum_required(VERSION 3.16)
project(odelib CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_library(odelib INTERFACE)
target_include_directories(odelib INTERFACE include)

function (add_ode_example name)
    add_executable(${name} examples/${name}.cpp)
    target_link_libraries(${name} PRIVATE odelib)
endfunction()

add_ode_example(decay_euler)
add_ode_example(decay_rk4)
add_ode_example(scaled_decay_rk4)
add_ode_example(scaled_decay_adaptive_rk4)
add_ode_example(harmonic_oscillator_rk4)
add_ode_example(harmonic_oscillator_adaptive_rk4)
add_ode_example(harmonic_oscillator_rkdp)
add_ode_example(harmonic_oscillator_adaptive_rkdp)
add_ode_example(gbm_euler_maruyama)
add_ode_example(gbm_milstein)
add_ode_example(black_scholes)
add_ode_example(black_scholes_multithread)

enable_testing()
add_subdirectory(tests)
add_subdirectory(benchmarks)