function(add_ode_test name)
    add_executable(${name} ${name}.cpp)
    target_link_libraries(${name} PRIVATE odelib)
    add_test(NAME ${name} COMMAND ${name})
endfunction()

add_ode_test(test_euler)
add_ode_test(test_rk4)
add_ode_test(test_scaled_decay_rk4)
add_ode_test(test_harmonic_oscillator_rk4)
add_ode_test(test_harmonic_oscillator_adaptive_rk4)
add_ode_test(test_harmonic_oscillator_rkdp)
add_ode_test(test_harmonic_oscillator_adaptive_rkdp)
add_ode_test(test_gbm_euler_maruyama)
add_ode_test(test_gbm_milstein)
add_ode_test(test_heston_model)